export enum PrimaryMuscle {
  MIDDLE_BACK = 'middle back',
  LATS = 'lats',
  ABDOMINALS = 'abdominals',
  LOWER_BACK = 'lower back',
  FOREARMS = 'forearms',
  ABDUCTORS = 'abductors',
  TRAPS = 'traps',
  HAMSTRINGS = 'hamstrings',
  QUADRICEPS = 'quadriceps',
  CHEST = 'chest',
  BICEPS = 'biceps',
  ADDUCTORS = 'adductors',
  NECK = 'neck',
  CALVES = 'calves',
  SHOULDERS = 'shoulders',
  TRICEPS = 'triceps',
  GLUTES = 'glutes',
}
