export enum AppRoutes {
  EXERCISES = '/exercises',
  HOME = '/',
  MY_PROFILE = '/my-profile',
  MY_TRAINING = '/my-training',
  OPTIONS = '/options',
  PASSWORD_CHANGE = '/passwordReset',
  REGISTRATION_VERIFICATION = '/registerVerification',
  ROUTINES = '/routines',
  ROUTINE_CREATE = '/routines/routine-create',
  ROUTINE_DETAILS = '/routines/routine-details/:routineId',
  ROUTINE_UPDATE = '/routines/routine-update/:routineId',
  WORKOUT = '/my-training/:workoutId',
  WORKOUT_CREATE = '/my-training/new',
}
